# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeBuilder, monadControl, monadLogger, mtl, text, time
, transformers, transformersBase
}:

cabal.mkDerivation (self: {
  pname = "groundhog";
  version = "0.7.0.1";
  sha256 = "1g50qwwxp999g1r8486vqr12facmlxy6nz9vz412v6y469ww5b1x";
  buildDepends = [
    blazeBuilder monadControl monadLogger mtl text time transformers
    transformersBase
  ];
  meta = {
    homepage = "http://github.com/lykahb/groundhog";
    description = "Type-safe datatype-database mapping library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
