# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, groundhog, text, time, unorderedContainers, yaml }:

cabal.mkDerivation (self: {
  pname = "groundhog-th";
  version = "0.7.0";
  sha256 = "14g4665wrr3226m2v63p4j8g9bcyi5la7nk2vh509xyz3z17aq67";
  buildDepends = [
    aeson groundhog text time unorderedContainers yaml
  ];
  meta = {
    description = "Type-safe datatype-database mapping library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
