# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, directSqlite, groundhog, monadControl, monadLogger
, resourcePool, text, transformers, unorderedContainers
}:

cabal.mkDerivation (self: {
  pname = "groundhog-sqlite";
  version = "0.7.0.1";
  sha256 = "0lsm9yfapdpy4nf5bxrbjkvw9nwc82qfmyw1h9l3mc4b8nfp12dy";
  buildDepends = [
    directSqlite groundhog monadControl monadLogger resourcePool text
    transformers unorderedContainers
  ];
  meta = {
    description = "Sqlite3 backend for the groundhog library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
